Fix typo
etalab/datagouvfr-pages pull request #40
Opened 2022-02-05 17:54 UTC by bzg

See https://github.com/etalab/datagouvfr-pages/pull/37#pullrequestreview-873944786

2022-02-05 18:02 UTC, RLesur commented
Thanks! I close https://github.com/etalab/datagouvfr-pages/pull/39.

2022-02-05 18:04 UTC, RLesur requested changes

2022-02-05 18:04 UTC, RLesur commented on pages/legal/licences.md
> +| [European Union Public License 2.0](https://spdx.org/licenses/EUPL-1.2.html#licenseText)                        | `EUPL-1.2`          |
The typo is present twice:

```suggestion
| [European Union Public License 1.2](https://spdx.org/licenses/EUPL-1.2.html#licenseText)                        | `EUPL-1.2`          |

```

2022-02-07 07:51 UTC, merged

2022-02-07 12:55 UTC, agarrone commented
Thanks !